"""create balance sheets table

Revision ID: 3c91f346582c
Revises: deed05b70933
Create Date: 2026-07-31 17:44:11.333668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c91f346582c'
down_revision: Union[str, Sequence[str], None] = 'deed05b70933'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('balance_sheets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('period_end_date', sa.Date(), nullable=False),
    sa.Column('period_type', sa.String(length=20), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('total_assets', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('current_assets', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('cash_and_cash_equivalents', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('inventory', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('accounts_receivable', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('total_non_current_assets', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('property_plant_equipment', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('goodwill', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('intangible_assets', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('total_liabilities', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('current_liabilities', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('accounts_payable', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('short_term_debt', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('total_non_current_liabilities', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('long_term_debt', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('total_debt', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('stockholders_equity', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('retained_earnings', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'period_end_date', 'period_type', name='uq_balance_sheets_asset_period')
    )
    op.create_index(op.f('ix_balance_sheets_asset_id'), 'balance_sheets', ['asset_id'], unique=False)
    op.create_index(op.f('ix_balance_sheets_id'), 'balance_sheets', ['id'], unique=False)
    op.create_index(op.f('ix_balance_sheets_period_end_date'), 'balance_sheets', ['period_end_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_balance_sheets_period_end_date'), table_name='balance_sheets')
    op.drop_index(op.f('ix_balance_sheets_id'), table_name='balance_sheets')
    op.drop_index(op.f('ix_balance_sheets_asset_id'), table_name='balance_sheets')
    op.drop_table('balance_sheets')
    # ### end Alembic commands ###
