"""create data providers table

Revision ID: 52b58047a2af
Revises: 0c2925cf40e9
Create Date: 2026-07-28 21:49:46.358713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52b58047a2af'
down_revision: Union[str, Sequence[str], None] = '0c2925cf40e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('provider_type', sa.String(length=50), nullable=False),
    sa.Column('base_url', sa.String(length=255), nullable=True),
    sa.Column('api_key_env_name', sa.String(length=100), nullable=True),
    sa.Column('priority', sa.Integer(), server_default='100', nullable=False),
    sa.Column('rate_limit_per_minute', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_providers_enabled'), 'data_providers', ['enabled'], unique=False)
    op.create_index(op.f('ix_data_providers_name'), 'data_providers', ['name'], unique=True)
    op.create_index(op.f('ix_data_providers_priority'), 'data_providers', ['priority'], unique=False)
    op.create_index(op.f('ix_data_providers_provider_type'), 'data_providers', ['provider_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_providers_provider_type'), table_name='data_providers')
    op.drop_index(op.f('ix_data_providers_priority'), table_name='data_providers')
    op.drop_index(op.f('ix_data_providers_name'), table_name='data_providers')
    op.drop_index(op.f('ix_data_providers_enabled'), table_name='data_providers')
    op.drop_table('data_providers')
    # ### end Alembic commands ###
