"""add income statements table

Revision ID: deed05b70933
Revises: b6cfde45d59c
Create Date: 2026-07-31 16:02:34.913997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'deed05b70933'
down_revision: Union[str, Sequence[str], None] = 'b6cfde45d59c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('income_statements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('period_end_date', sa.Date(), nullable=False),
    sa.Column('period_type', sa.String(length=20), nullable=False),
    sa.Column('currency', sa.String(length=20), nullable=True),
    sa.Column('total_revenue', sa.BigInteger(), nullable=True),
    sa.Column('cost_of_revenue', sa.BigInteger(), nullable=True),
    sa.Column('gross_profit', sa.BigInteger(), nullable=True),
    sa.Column('operating_expense', sa.BigInteger(), nullable=True),
    sa.Column('operating_income', sa.BigInteger(), nullable=True),
    sa.Column('net_non_operating_interest_income_expense', sa.BigInteger(), nullable=True),
    sa.Column('pretax_income', sa.BigInteger(), nullable=True),
    sa.Column('tax_provision', sa.BigInteger(), nullable=True),
    sa.Column('net_income', sa.BigInteger(), nullable=True),
    sa.Column('diluted_average_shares', sa.BigInteger(), nullable=True),
    sa.Column('diluted_eps', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'period_end_date', 'period_type', name='uq_income_statements_asset_period')
    )
    op.create_index(op.f('ix_income_statements_asset_id'), 'income_statements', ['asset_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_income_statements_asset_id'), table_name='income_statements')
    op.drop_table('income_statements')
    # ### end Alembic commands ###
